import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="w-full flex justify-center py-4 mb-4 bg-gray-100 border-b">
<<<<<<< HEAD:App/src/app/layout.tsx
          <Link href="/" className="mx-4 font-semibold text-black hover:underline">Home</Link>
          <Link href="/feedback" className="mx-4 font-semibold text-blue-600 hover:underline">Feedback</Link>
=======
          <Link
            href="/"
            className="mx-4 font-semibold text-black hover:underline"
          >
            Home
          </Link>
          <Link
            href="/feedback"
            className="mx-4 font-semibold text-blue-600 hover:underline"
          >
            Feedback
          </Link>
>>>>>>> bdbc379 (Flattened and Added Langflow as a container):webserver/app/src/app/layout.tsx
        </nav>
        {children}
      </body>
    </html>
  );
}
