# Langflow Image
# Use python3.12-slim as the base image
# FROM docker.io/library/python:3.12-slim
#FROM python:3.12-slim-bookworm
#COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
FROM docker.io/langflowai/langflow:latest

# FIXME: DO_NOT_TRACK=true
WORKDIR /app
#ADD uv.lock /app
#ADD pyproject.toml /app
#ADD requirements.txt /app
#RUN uv venv
# Sync the project into a new environment, asserting the lockfile is up to date
#RUN . .venv/bin/activate && uv sync --locked
# Set the working directory
# Build the Next.js application

# Copy the project into the image
#WORKDIR /app/flows
#COPY flows/*.json /app/flows/
#ENV LANGFLOW_LOAD_FLOWS_PATH=/app/flows

# Expose the port the app runs on
EXPOSE 7860
EXPOSE 8080
# Switch to non-root user
#USER 1001

# Start the application
#CMD ["uv","run", "langflow","run"]
# Command to run Langflow
CMD ["python", "-m", "langflow", "run", "--host", "0.0.0.0", "--port", "7860"]