[project]
name = "langflow_server"
version = "0.1.0"
description = "Langflow Server for managing and serving Backend"
readme = "README.md"
requires-python = ">=3.12,<=3.13"
dependencies = ["langflow"]
